# Generated by Django 3.1.4 on 2021-01-10 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votings',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='votings',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votings',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='votings',
            name='times_voted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votings',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='votings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
