# Generated by Django 3.1.4 on 2021-01-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210110_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votings',
            name='author',
        ),
        migrations.AlterField(
            model_name='votings',
            name='comments_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votings',
            name='description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='votings',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votings',
            name='name',
            field=models.TextField(default='Ellections'),
        ),
    ]
