# Generated by Django 3.1.5 on 2021-01-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20210121_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='date_created',
            field=models.TextField(default='30/02/0001'),
        ),
        migrations.AlterField(
            model_name='votings',
            name='name',
            field=models.TextField(default='Voting'),
        ),
        migrations.AlterField(
            model_name='votings',
            name='question',
            field=models.TextField(default='Question'),
        ),
        migrations.CreateModel(
            name='voting_answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='Answer')),
                ('times_selected', models.IntegerField(default=0)),
                ('voting_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.votings')),
            ],
        ),
        migrations.CreateModel(
            name='voted_user_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voted_person_email', models.TextField(default='@mail.ru')),
                ('voting_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.votings')),
            ],
        ),
    ]
