# Generated by Django 3.1.5 on 2021-01-27 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0006_auto_20210121_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voted_user_record',
            name='voted_person_email',
        ),
        migrations.AddField(
            model_name='voted_user_record',
            name='voted_person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votings',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(default='')),
                ('description', models.TextField(default='No Description')),
                ('date_added', models.TextField(default='30/02/0001')),
                ('is_answered', models.BooleanField(default=False)),
                ('answer', models.TextField(default='')),
                ('date_answer', models.TextField(default='30/02/0001')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.votings')),
            ],
        ),
    ]
